version: '2'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8085:8085

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080

  user-registration-service:
    build: user-registration-service/
    depends_on:
      - eureka-server
      - mongo
      - rabbitmq
    restart: always
    network_mode: "host"
    image: user-registration-service
    hostname: localhost
    ports:
      - 8099:8099

  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo-service
    network_mode: "host"
    hostname: localhost
    volumes:
      - /data/mongo:/data/

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    network_mode: "host"
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: userDB
      MYSQL_PASSWORD: Root@123
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"


  user-login-service:
    build: user-login-service/
    depends_on:
     - eureka-server
     - mysql
     - rabbitmq
    restart: always
    network_mode: "host"
    image: user-login-service
    hostname: localhost
    ports:
    - 8088:8088

  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: localhost
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
